import '@servicenow/sdk/global'
import { BusinessRule, ClientScript } from '@servicenow/sdk/core'
import { showStateUpdate } from '../server/script.js'

//creates a client script that pops up 'Table loaded successfully!!' message every time todo record is loaded
ClientScript({
    $id: Now.ID['cs0'],
    name: 'my_client_script',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! 🚀")
        
        // Add a fun button to change form colors
        setTimeout(function() {
            var button = document.createElement('button');
            button.innerHTML = '🎨 Make it Rainbow!';
            button.style.cssText = 'position: fixed; top: 10px; right: 10px; z-index: 1000; padding: 10px; background: linear-gradient(45deg, red, orange, yellow, green, blue, indigo, violet); color: white; border: none; border-radius: 5px; cursor: pointer; font-weight: bold;';
            button.onclick = function() {
                var colors = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#FFA07A', '#98D8C8', '#FFD93D', '#6BCF7F'];
                var randomColor = colors[Math.floor(Math.random() * colors.length)];
                document.body.style.background = 'linear-gradient(135deg, ' + randomColor + ', white)';
                g_form.addInfoMessage('🌈 Form color changed! You made it fun! 🎉');
            };
            document.body.appendChild(button);
        }, 1000);
    }`,
})

//creates a business rule that pops up state change message whenever a todo record is updated
BusinessRule({
    $id: Now.ID['br0'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange',
    order: 100,
    when: 'after',
    active: true,
})