import { BusinessRule, ClientScript } from '@servicenow/sdk/core'
import '@servicenow/sdk/global'
import { showStateUpdate } from '../server/script.js'

//creates a client script that pops up 'Table loaded MUHAHAHAHAHAHAH!!' message every time todo record is loaded
ClientScript({
    $id: Now.ID['cs0'],
    name: 'my_client_script',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! 🚀🚀🚀🚀🚀🚀🚀🚀🚀")
        
        // Add a fun button to change form colors - works in both classic and workspace
        setTimeout(function() {
            var button = document.createElement('button');
            button.innerHTML = '🎨 Make it Rainbow!';
            button.style.cssText = 'position: fixed; top: 10px; right: 10px; z-index: 9999; padding: 10px; background: linear-gradient(45deg, red, orange, yellow, green, blue, indigo, violet); color: white; border: none; border-radius: 5px; cursor: pointer; font-weight: bold; box-shadow: 0 2px 10px rgba(0,0,0,0.3);';
            button.onclick = function() {
                var colors = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#FFA07A', '#98D8C8', '#FFD93D', '#6BCF7F'];
                var randomColor = colors[Math.floor(Math.random() * colors.length)];
                
                // Try different selectors for classic vs workspace
                var targetElement = document.querySelector('.sn-workspace') ||
                                   document.querySelector('.sn-form-layout') ||
                                   document.querySelector('body') ||
                                   document.querySelector('html');
                
                if (targetElement) {
                    targetElement.style.background = 'linear-gradient(135deg, ' + randomColor + ', white)';
                    g_form.addInfoMessage('🌈 Form color changed! You made it fun! 🎉');
                    
                    // Add some extra fun - animate the button
                    button.style.transform = 'scale(1.1) rotate(5deg)';
                    setTimeout(function() {
                        button.style.transform = 'scale(1) rotate(0deg)';
                    }, 300);
                } else {
                    g_form.addInfoMessage('⚠️ Could not find element to color, but still fun! 😊');
                }
            };
            
            // Try to append to different containers based on UI
            var targetContainer = document.querySelector('.sn-workspace') ||
                                document.querySelector('.sn-form-layout') ||
                                document.querySelector('body');
            
            if (targetContainer) {
                targetContainer.appendChild(button);
                g_form.addInfoMessage('🎨 Rainbow button added! Click me! 🌈');
            } else {
                // Fallback - just add to body
                document.body.appendChild(button);
                g_form.addInfoMessage('🎨 Rainbow button added (fallback)! Click me! 🌈');
            }
        }, 2000); // Increased delay to ensure form is fully loaded
    }`,
})

//creates a business rule that pops up state change message whenever a todo record is updated
BusinessRule({
    $id: Now.ID['br0'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange',
    order: 100,
    when: 'after',
    active: true,
})