import { BusinessRule, ClientScript } from '@servicenow/sdk/core'
import '@servicenow/sdk/global'
import { showStateUpdate } from '../server/script.js'

//creates a client script that pops up 'Table loaded MUHAHAHAHAHAHAH!!' message every time todo record is loaded
ClientScript({
    $id: Now.ID['cs0'],
    name: 'my_client_script',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! 🚀🚀🚀🚀🚀🚀🚀🚀🚀");

    setTimeout(function() {
        try {
            g_form.addInfoMessage("[RainbowButton] Starting script execution.");

            // Create the button
            var button = document.createElement('button');
            button.innerHTML = '🎨 Make it Rainbow!';
            button.style.cssText = 'position: fixed; top: 10px; right: 10px; z-index: 9999; padding: 10px; background: linear-gradient(45deg, red, orange, yellow, green, blue, indigo, violet); color: white; border: none; border-radius: 5px; cursor: pointer; font-weight: bold; box-shadow: 0 2px 10px rgba(0,0,0,0.3);';

            // Define the click handler
            button.onclick = function() {
                var colors = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#FFA07A', '#98D8C8', '#FFD93D', '#6BCF7F'];
                var randomColor = colors[Math.floor(Math.random() * colors.length)];
                
                var colorTarget = document.querySelector('.now-modal-dialog-body') || // Workspace Modal
                                  document.querySelector('.sn-component-workspace-main') || // Workspace Main Area
                                  document.body; // Fallback to body

                if (colorTarget) {
                    colorTarget.style.background = 'linear-gradient(135deg, ' + randomColor + ', white)';
                    g_form.addInfoMessage('🌈 Form color changed! You made it fun! 🎉');
                    button.style.transform = 'scale(1.1) rotate(5deg)';
                    setTimeout(function() { button.style.transform = 'scale(1) rotate(0deg)'; }, 300);
                } else {
                    g_form.addInfoMessage('⚠️ [RainbowButton] Could not find an element to apply color to.');
                }
            };

            // Determine the environment and find the container
            var targetContainer = null;
            if (typeof g_aw !== 'undefined') {
                g_form.addInfoMessage("[RainbowButton] Agent Workspace detected. Searching for workspace container...");
                // In Workspace, we need to find the right frame/element.
                targetContainer = document.querySelector('.now-modal-dialog-body') || document.querySelector('.sn-component-workspace-main');
            } else {
                g_form.addInfoMessage("[RainbowButton] Classic UI detected. Using document.body.");
                targetContainer = document.body;
            }

            // Append the button
            if (targetContainer) {
                targetContainer.appendChild(button);
                g_form.addInfoMessage('🎨 [RainbowButton] Button appended successfully! Click me! 🌈');
            } else {
                g_form.addInfoMessage('❌ [RainbowButton] FAILED: Could not find a suitable container to attach the button.');
            }

        } catch (e) {
            g_form.addInfoMessage('❌ [RainbowButton] FAILED with an error: ' + e.message);
        }
    }, 3000);
    }`,
})

//creates a business rule that pops up state change message whenever a todo record is updated
BusinessRule({
    $id: Now.ID['br0'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange',
    order: 100,
    when: 'after',
    active: true,
})